# Generated by Django 2.2.7 on 2020-04-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tollgate', '0002_tollgates_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollgatelogs',
            name='min_charge',
        ),
        migrations.AddField(
            model_name='tollgates',
            name='min_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
