# Generated by Django 2.2.7 on 2020-04-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=12, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Sugar Donation Entry',
                'verbose_name_plural': 'Sugar Donation Entries',
                'db_table': 'tbl_sugarcamp',
            },
        ),
    ]
