# Generated by Django 2.2.7 on 2020-06-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200607_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoItems',
        ),
    ]
