# Generated by Django 2.2.7 on 2020-07-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_deviceinfo_is_admin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='comments',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
