# Generated by Django 2.2.7 on 2020-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200401_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vtype',
            field=models.IntegerField(blank=True, choices=[(0, 'Unicycle'), (1, '2 wheeler'), (2, '3 wheeler'), (3, '4 wheeler'), (4, 'Heavy passenger motor vehicle'), (5, 'Heavy goods motor vehicle')], max_length=50, null=True),
        ),
    ]
