# Generated by Django 2.2.7 on 2020-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20200401_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vtype',
            field=models.IntegerField(blank=True, choices=[(0, 'Unicycle'), (1, '2 wheeler'), (2, '3 wheeler'), (3, '4 wheeler'), (4, 'Heavy passenger motor vehicle'), (5, 'Heavy goods motor vehicle')], null=True),
        ),
    ]
