# Generated by Django 2.2.7 on 2020-04-11 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_auto_20200403_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='reg_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9]+$')]),
        ),
    ]
