# Generated by Django 2.2.7 on 2020-04-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_wallettransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='ttype',
            field=models.CharField(blank=True, choices=[(0, 'Add Money'), (1, 'Toll Charge')], max_length=120, null=True),
        ),
    ]
