# Generated by Django 2.2.7 on 2020-04-03 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_wallettransactions_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
