# Generated by Django 2.2.7 on 2020-04-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_wallettransactions_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactions',
            name='ttype',
            field=models.IntegerField(blank=True, choices=[(0, 'Add Money'), (1, 'Toll Charge')], max_length=120, null=True),
        ),
    ]
