# Generated by Django 2.2.7 on 2020-04-03 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tollgate', '0003_auto_20200402_1859'),
        ('accounts', '0013_auto_20200403_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tollbillings',
            name='tollgate',
        ),
        migrations.AddField(
            model_name='tollbillings',
            name='tollgate_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_toll_bill', to='tollgate.Tollgates'),
        ),
        migrations.AddField(
            model_name='tollbillings',
            name='tollgate_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='out_toll_bill', to='tollgate.Tollgates'),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='ttype',
            field=models.IntegerField(blank=True, choices=[(0, 'Add Money'), (1, 'Toll Charge')], null=True),
        ),
    ]
