# Generated by Django 2.2.7 on 2020-04-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200403_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollbillings',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
