# Generated by Django 2.2.7 on 2020-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_tollbillings_ticket_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransactions',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
