# Generated by Django 2.2.7 on 2020-04-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_wallettransactions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tollbillings',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
