# Generated by Django 2.2.7 on 2020-06-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200404_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='tollbillings',
            name='distance',
            field=models.FloatField(default=0),
        ),
    ]
